function [fitresult, gof] = createFit(X, Y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'ExpFit' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Dec-2018 02:32:24


%% Fit: 'ExpFit'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'y0 + A1*(1 - exp(-x/t1)) + A2*(1 - exp(-x/t2))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.550156342898422 0.622475086001227 0.587044704531417 0.207742292733028 0.301246330279491];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% A1 = fitresult.A1;
% A2 = fitresult.A2;
% t1 = fitresult.t1;
% t2 = fitresult.t2;
% y0 = fitresult.y0;
% RMSE=gof.rmse;

% Out put to xsls

end
